import { DataInterface } from './DataInterface';

export const DATA: DataInterface[] = [
  {
    name: 'I want a detailed tech stack of video annotation',
    days: '6 days left',
    price: '$30',
    text: 'Avg Bid',
    description:
      'Supposed to build an application that annotate a video. I want the details of the process and the tech stack of this project. ',
    bids: '1 bids',
    tag1: 'App Developer',
    tag2: 'Computer Vision',
    tag3: 'Machine Learning',
    tag4: 'Aritificial Intelligence',
  },
  {
    name: 'Social Media Creatives ',
    days: '6 days left',
    price: '$33',
    text: 'Avg Bid',
    description:
      'Want to promote our business on social media platforms, we require a high end graphic designer who can design creative as per our business needs  ',
    bids: '2 bids',
    tag1: 'Banner Design',
    tag2: ' Facebook Marketing ',
    tag3: 'Graphic Design',
  },
  {
    name: 'document editing ',
    days: '6 days left',
    price: '$41',
    text: 'Avg Bid',
    description: 'require a document edited with my requirements  ',
    bids: '1 bids',
    tag1: 'Computer Graphics  ',
    tag2: 'Copy Editing',
    tag3: 'Copywriting',
  },
  {
    name: 'Sell My air purifier',
    days: '6 days left',
    price: '$102',
    text: 'Avg Bid',
    description:
      "In this situation of Covid-19 our country is suffering from various problems. I have bought you a product which is an Air purifier which is one of the best and most used purifier. It has lots of features such as it increases our oxygen level. I don't force you to buy this purifier but I recommend you that it can be very useful. ",
    bids: '1 bids',
    tag1: 'Communications   ',
    tag2: 'Facebook Marketing',
    tag3: 'Internet Marketing',
  },
  {
    name: 'e-commerce application',
    days: '6 days left',
    price: '$170',
    text: 'Avg Bid',
    description: 'sell and buy e-commerce application for ios and android ',
    bids: '1 bids',
    tag1: ' Android ',
    tag2: 'eCommerce',
    tag3: 'Mobile App',
    tag4: 'iPhone',
  },
  {
    name: 'I want a detailed tech stack of video annotation',
    days: '6 days left',
    price: '$30',
    text: 'Avg Bid',
    description:
      'Supposed to build an application that annotate a video. I want the details of the process and the tech stack of this project. ',
    bids: '1 bids',
    tag1: 'App Developer',
    tag2: 'Computer Vision',
    tag3: 'Machine Learning',
    tag4: 'Aritificial Intelligence',
  },
  {
    name: 'Social Media Creatives ',
    days: '6 days left',
    price: '$33',
    text: 'Avg Bid',
    description:
      'Want to promote our business on social media platforms, we require a high end graphic designer who can design creative as per our business needs  ',
    bids: '2 bids',
    tag1: 'Banner Design',
    tag2: ' Facebook Marketing ',
    tag3: 'Graphic Design',
  },
  {
    name: 'document editing ',
    days: '6 days left',
    price: '$41',
    text: 'Avg Bid',
    description: 'require a document edited with my requirements  ',
    bids: '1 bids',
    tag1: 'Computer Graphics  ',
    tag2: 'Copy Editing',
    tag3: 'Copywriting',
  },
  {
    name: 'Sell My air cooler',
    days: '6 days left',
    price: '$172',
    text: 'Avg Bid',
    description:
      'I have bought you a product which is an Air purifier which is one of the best and most used purifier. It has lots of features such as it increases our oxygen level. ',
    bids: '1 bids',
    tag1: 'Communications   ',
    tag2: 'Facebook Marketing',
    tag3: 'Internet Marketing',
  },
  {
    name: 'e application',
    days: '6 days left',
    price: '$180',
    text: 'Avg Bid',
    description: 'sell and buy e application for ios and android ',
    bids: '1 bids',
    tag1: ' Android ',
    tag2: 'eCommerce',
    tag3: 'Mobile App',
    tag4: 'iPhone',
  },
];
